// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> nl = {
  "rp_card_title": "Dichtsbijzijnde punten",
  "rp_card_title_loading": "Bezig met het laden...",
  "rp_card_title_empty": "Geen punten gevonden bij u in de buurt",
  "rp_card_subtitle": "De volgende punten staan ​​het dichtst bij u:",
  "rp_card_subtitle_loading": "Even geduld a.u.b. terwijl we de dichtstbijzijnde recyclepunten laden",
  "rp_card_subtitle_empty": "We konden geen recyclepunten identificeren",
  "radius_card_title": "Wijzig zoekradius",
  "radius_card_subtitle": "Wijzig de afstand voor meer recyclepunten",
  "radius_card_button": "Verander afstand",
  "expanded_menu_login": "Inloggen",
  "expanded_menu_settings": "Instellingen",
  "expanded_menu_about_us": "Over Ons",
  "expanded_menu_logout": "Uitloggen",
  "login_title": "Log in op uw account",
  "login_subtitle": "Voer uw inloggegevens in om door te gaan",
  "login_email_field": "E-mail",
  "login_password_field": "Wachtwoord",
  "login_button": "Inloggen",
  "login_google_button": "Inloggen met Google",
  "login_create_account_button": "Creëer een account",
  "create_account_title": "Creëer een account",
  "create_account_subtitle": "Vul de verplichte velden in om een ​​account aan te maken",
  "create_account_lastname_field": "Voornaam",
  "create_account_firstname_field": "Familienaam",
  "create_account_email_field": "E-mail",
  "create_account_password_field": "Wachtwoord",
  "create_account_repeat_password_field": "Herhaal wachtwoord",
  "create_account_button": "Creëer account",
  "create_account_google_button": "Inloggen met Google",
  "create_account_create_account_button": "Account aanmaken",
  "profile_title": "Profiel",
  "profile_card_personal_title": "Persoonlijke informatie",
  "profile_card_security_title": "Veiligheid",
  "profile_card_danger_title": "Gevarenzone",
  "profile_card_delete_account": "Account verwijderen",
  "profile_card_change_password": "Wachtwoord wijzigen",
  "material_glass": "Glas",
  "material_plastic": "Plastiek",
  "material_paper": "Papier",
  "details_materials_title": "Materialen die u kunt recyclen",
  "detail_glass_card_title": "What is glass?",
  "detail_paper_card_title": "What is paper?",
  "detail_plastic_card_title": "What is plastic?",
  "detail_glass_card_description": "For the most part, glassware that is used in the kitchen and for food items is completely recyclable. Items such as condiment containers, food storage, jars, and more can be put in your recycling bin. However, not all glass is the same. An easy way to know if your glass can be recycled is by looking at its recycling code. If it is an approved code by your recycling program, then it is likely safe to put in the recycling bin!",
  "detail_paper_card_description": "Many different kinds of paper can be recycled, including white office paper, newspaper, colored office paper, cardboard, white computer paper, magazines, catalogs, and phone books. Types of paper that are not recyclable are coated and treated paper, paper with food waste, juice and cereal boxes, paper cups, paper towels, and paper or magazine laminated with plastic.",
  "detail_plastic_card_description": "Many different kinds of paper can be recycled, including white office paper, newspaper, colored office paper, cardboard, white computer paper, magazines, catalogs, and phone books. Types of paper that are not recyclable are coated and treated paper, paper with food waste, juice and cereal boxes, paper cups, paper towels, and paper or magazine laminated with plastic.",
  "navigation_card_tilte": "Recyclepoint geselecteerd",
  "settings_title": "Instellingen",
  "settings_subtitle": "Wijzig applicatie instellingen",
  "about_us_title": "About us",
  "about_us_subtitle": "Leer ons beter kennen",
  "about_us_about_us_card_title": "Wie zijn wij?",
  "about_us_about_us_card_description": "SuReSur is in 2015 opgericht. We zijn in april 2015 na de voorbereidingsfase met het project gestart. Stichting wil graag een voortrekkers rol vervullen in het bewustmaken van de Surinaamse bevoking op het gebied van recyclen. Dit wil ze doen door onder andere landelijk in totaal 450 verzamelbakken op strategische plekken plaatsen waar de plastic flessen en aluminium blikken worden ingezameld. Het is de bedoeling dat deze ingezamelde flessen en blikken worden afgevoerd naar een recyclebedrijf.",
  "about_us_contact_card_title": "Contact",
  "settings_appearance_card_title": "Uiterlijk",
  "settings_dark_mode": "Nacht modus",
  "language_dark_mode": "Taal",
  "quick_find_title": "Quick Find",
  "quick_find_subtitle": "Quickly find the nearest recyclepoint",
  "quick_find_materials_title": "Materials to recycle",
  "quick_find_radius": "Search radius",
  "quick_find_summary": "summary",
  "quick_find_radius_to_search": "Radius to search {} KM",
  "quick_find_no_material_error_title": "Something went wrong...",
  "quick_find_no_material_error_description": "Please select a material type",
  "quick_find_rp_found_title": "Recyclepoint found...",
  "quick_find_rp_found_description": "Recyclepoint {} found - {}",
  "quick_find_rp_not_found_error_title": "Sorry...",
  "quick_find_rp_not_found_error_description": "No recyclepoints found",
  "quick_find_rp_found_navigate_button": "Navigate to recyclepoint",
  "quick_find_rp_found_cancel_button": "Cancel"
};
static const Map<String,dynamic> en = {
  "rp_card_title": "Points near you",
  "rp_card_title_loading": "Loading points near you",
  "rp_card_title_empty": "No Points found near you",
  "rp_card_subtitle": "The following points are closest to you",
  "rp_card_subtitle_loading": "Please wait while we load the closest recyclepoints",
  "rp_card_subtitle_empty": "we were unable to identify recyclepoints",
  "radius_card_title": "Change search radius",
  "radius_card_subtitle": "Change the radius for more recycle locations",
  "radius_card_button": "change radius",
  "expanded_menu_login": "Login",
  "expanded_menu_settings": "Settings",
  "expanded_menu_about_us": "About us",
  "expanded_menu_logout": "Logout",
  "login_title": "Log into your account",
  "login_subtitle": "Enter your login credentials to continue",
  "login_email_field": "Email",
  "login_password_field": "Password",
  "login_button": "login",
  "login_google_button": "Sign in with Google",
  "login_create_account_button": "Create an account",
  "create_account_title": "Create an account",
  "create_account_subtitle": "fill in the required fields to create an account",
  "create_account_lastname_field": "Firstname",
  "create_account_firstname_field": "Lastname",
  "create_account_email_field": "Email",
  "create_account_password_field": "Password",
  "create_account_repeat_password_field": "Repeat Password",
  "create_account_button": "submit",
  "create_account_google_button": "Sign in with Google",
  "create_account_create_account_button": "Create an account",
  "profile_title": "Profile",
  "profile_card_personal_title": "Personal Info",
  "profile_card_security_title": "Security",
  "profile_card_danger_title": "Danger Zone",
  "profile_card_delete_account": "Delete Account",
  "profile_card_change_password": "change Password",
  "details_materials_title": "Materials you can recycle",
  "material_glass": "Glass",
  "material_plastic": "Plastic",
  "material_paper": "Paper",
  "detail_glass_card_title": "What is glass?",
  "detail_paper_card_title": "What is paper?",
  "detail_plastic_card_title": "What is plastic?",
  "detail_glass_card_description": "For the most part, glassware that is used in the kitchen and for food items is completely recyclable. Items such as condiment containers, food storage, jars, and more can be put in your recycling bin. However, not all glass is the same. An easy way to know if your glass can be recycled is by looking at its recycling code. If it is an approved code by your recycling program, then it is likely safe to put in the recycling bin!",
  "detail_paper_card_description": "Many different kinds of paper can be recycled, including white office paper, newspaper, colored office paper, cardboard, white computer paper, magazines, catalogs, and phone books. Types of paper that are not recyclable are coated and treated paper, paper with food waste, juice and cereal boxes, paper cups, paper towels, and paper or magazine laminated with plastic.",
  "detail_plastic_card_description": "Many different kinds of paper can be recycled, including white office paper, newspaper, colored office paper, cardboard, white computer paper, magazines, catalogs, and phone books. Types of paper that are not recyclable are coated and treated paper, paper with food waste, juice and cereal boxes, paper cups, paper towels, and paper or magazine laminated with plastic.",
  "navigation_card_tilte": "Recyclepoint selected",
  "about_us_title": "About us",
  "about_us_subtitle": "Learn more about us",
  "about_us_about_us_card_title": "Who are we?",
  "about_us_about_us_card_description": "SuReSur is in 2015 opgericht. We zijn in april 2015 na de voorbereidingsfase met het project gestart. Stichting wil graag een voortrekkers rol vervullen in het bewustmaken van de Surinaamse bevoking op het gebied van recyclen. Dit wil ze doen door onder andere landelijk in totaal 450 verzamelbakken op strategische plekken plaatsen waar de plastic flessen en aluminium blikken worden ingezameld. Het is de bedoeling dat deze ingezamelde flessen en blikken worden afgevoerd naar een recyclebedrijf.",
  "about_us_contact_card_title": "Contact",
  "settings_title": "Settings",
  "settings_subtitle": "Change application settings",
  "settings_appearance_card_title": "Appearance",
  "settings_dark_mode": "Dark Mode",
  "language_dark_mode": "Language",
  "quick_find_title": "Quick Find",
  "quick_find_subtitle": "Quickly find the nearest recyclepoint",
  "quick_find_materials_title": "Materials to recycle",
  "quick_find_radius": "Search radius",
  "quick_find_summary": "summary",
  "quick_find_radius_to_search": "Radius to search {} KM",
  "quick_find_no_material_error_title": "Something went wrong...",
  "quick_find_no_material_error_description": "Please select a material type",
  "quick_find_rp_found_title": "Recyclepoint found...",
  "quick_find_rp_found_description": "Recyclepoint {} found - {}",
  "quick_find_rp_not_found_error_title": "Sorry...",
  "quick_find_rp_not_found_error_description": "No recyclepoints found",
  "quick_find_rp_found_navigate_button": "Navigate to recyclepoint",
  "quick_find_rp_found_cancel_button": "Cancel"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"nl": nl, "en": en};
}
